version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: tc-bus-api-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: tc-bus-api-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: tc.test.topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181